---
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
  pull_request:
    types: [opened, synchronize, reopened]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@just

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt

      - name: linting
        run: |
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Debug builds
        run: cargo build
